import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Image from "next/image";
import styles from "./privacy-policy.module.scss";
import heroBg from "@/assets/images/hero-section-bg-banner.png";
import heroImg from "@/assets/images/karya-heros.png";

export default function PrivacyPolicy() {
  return (
    <>
      <Navbar
        links={[
          { label: "Services", href: "#services" },
          { label: "How it works", href: "#steps" },
          { label: "FAQs", href: "#faqs" },
        ]}
      />
      <section className={styles.bannerSection}>
        <div className={styles.bannerBg}>
          <Image
            src={heroBg}
            alt="Banner Background"
            fill
            priority
            className={styles.bgImage}
          />
        </div>
        <div className={styles.heroImageWrapper}>
          <Image
            src={heroImg}
            alt="Karya Sync Team"
            width={420}
            height={220}
            className={styles.heroImage}
          />
        </div>
      </section>
      <main className={styles.contentSection}>
        <div className={styles.policyContent}>
          <h1>Privacy Policy</h1>
          <span className={styles.updatedBadge}>Updated at 2025-12-19</span>
          <p>
            <strong>Karya Sync</strong> ("we," "our," or "us") is committed to
            protecting your privacy. This Privacy Policy explains how your
            personal information is collected, used, and disclosed by Karya
            Sync.
          </p>
          <p>
            This Privacy Policy applies to our website, and its associated
            subdomains (collectively, our "Service") alongside our application,
            Karya Sync. By accessing or using our Service, you signify that you
            have read, understood, and agree to our collection, storage, use,
            and disclosure of your personal information as described in this
            Privacy Policy and our Terms of Service.
          </p>
          <h2>DEFINITIONS AND KEY TERMS</h2>
          <p>
            <strong>Cookie:</strong> Small amount of data generated by a website
            and saved by your web browser. It helps identify your browser,
            provide analytics, remember preferences like language or login
            information.
          </p>
          <p>
            <strong>Company:</strong> Refers to Karya Sync Private Limited,
            House No. 01, Sector-14A, Ashoka Society, Vasundhara, Ghaziabad, UP,
            responsible for your information under this Privacy Policy.
          </p>
          <p>
            <strong>Country:</strong> India.
          </p>
          <p>
            <strong>Customer:</strong> Any company, organization, or person that
            signs up to use Karya Sync services.
          </p>
          <p>
            <strong>Device:</strong> Any internet-connected device such as
            phone, tablet, or computer.
          </p>
          <p>
            <strong>IP Address:</strong> A number assigned to your device that
            can identify the location from which it connects to the internet.
          </p>
          <p>
            <strong>Personnel:</strong> Individuals employed by or contracted by
            Karya Sync.
          </p>
          <p>
            <strong>Personal Data:</strong> Any information that can identify a
            natural person directly or indirectly.
          </p>
          <p>
            <strong>Service:</strong> Services provided by Karya Sync.
          </p>
          <p>
            <strong>Third-party service:</strong> Advertisers, marketing
            partners, and others who provide content or services.
          </p>
          <p>
            <strong>Website:</strong> Karya Sync website accessible via{" "}
            <a
              href="https://karyasync.com/"
              target="_blank"
              rel="noopener noreferrer">
              https://karyasync.com/
            </a>
          </p>
          <p>
            <strong>You:</strong> Any person or entity registered to use Karya
            Sync services.
          </p>
          <h2>WHAT INFORMATION DO WE COLLECT?</h2>
          <p>
            We collect information when you visit our app, register, place an
            order, subscribe to newsletters, respond to surveys, or fill out
            forms.
          </p>
          <p>Collected information includes:</p>
          <ul>
            <li>Name / Username</li>
            <li>Phone Number</li>
          </ul>
          <p>
            We may also collect optional mobile device information to improve
            user experience.
          </p>
          <h2>HOW DO WE USE THE INFORMATION WE COLLECT?</h2>
          <p>We use your information to:</p>
          <ul>
            <li>Personalize your experience</li>
            <li>Improve our app and services</li>
            <li>Improve customer support</li>
            <li>Process transactions</li>
            <li>Run contests, promotions, or surveys</li>
            <li>Send periodic emails</li>
          </ul>
          <h2>USE OF INFORMATION FROM THIRD PARTIES</h2>
          <p>
            Karya Sync may collect end-user data required to provide services.
            If users provide information via social media, publicly available
            data may also be collected. Privacy settings on social platforms
            control how much data is shared.
          </p>
          <h2>SHARING INFORMATION WITH THIRD PARTIES</h2>
          <p>
            We may share personal and non-personal information with advertisers,
            partners, affiliates, service providers, or during business
            restructuring such as mergers or asset sales.
          </p>
          <p>
            We may also share data for analytics, legal compliance, fraud
            prevention, and to protect rights and safety.
          </p>
          <h2>EMAIL COMMUNICATION</h2>
          <p>
            By submitting your email, you agree to receive emails from us. You
            can unsubscribe anytime using the link in emails. We do not send
            spam. Emails may also be used for targeted advertising with
            platforms like Facebook.
          </p>
          <h2>DATA RETENTION</h2>
          <p>
            We retain your data only as long as necessary to provide services or
            comply with legal obligations. When no longer required, data is
            deleted or anonymized.
          </p>
          <h2>DATA SECURITY</h2>
          <p>
            We use SSL encryption and secure servers to protect your data.
            However, no system is 100% secure, and absolute security cannot be
            guaranteed.
          </p>
          <h2>INTERNATIONAL DATA TRANSFER</h2>
          <p>
            Data may be transferred and stored outside India. By using our
            services, you consent to such transfers.
          </p>
          <h2>UPDATING OR DELETING INFORMATION</h2>
          <p>
            Customers may request updates, corrections, or deletion of personal
            data by contacting us or cancelling their account. Backup copies may
            exist temporarily.
          </p>
          <h2>PERSONNEL INFORMATION</h2>
          <p>Employee and applicant data is collected for HR purposes only.</p>
          <h2>SALE OF BUSINESS</h2>
          <p>
            In case of merger, sale, or bankruptcy, data may be transferred to
            third parties who agree to follow this Privacy Policy.
          </p>
          <h2>AFFILIATES</h2>
          <p>
            Data may be shared with corporate affiliates and will be treated
            according to this Privacy Policy.
          </p>
          <h2>GOVERNING LAW</h2>
          <p>
            This Privacy Policy is governed by the laws of India. Any disputes
            fall under Indian jurisdiction.
          </p>
          <h2>YOUR CONSENT</h2>
          <p>By using Karya Sync, you consent to this Privacy Policy.</p>
          <h2>LINKS TO OTHER WEBSITES</h2>
          <p>
            We are not responsible for third-party websites linked from our
            services.
          </p>
          <h2>COOKIES</h2>
          <p>
            Cookies are used to improve user experience. You may disable cookies
            via browser settings.
          </p>
          <h2>PAYMENT DETAILS</h2>
          <p>All payment information is stored securely.</p>
          <h2>KIDS’ PRIVACY</h2>
          <p>
            We do not knowingly collect data from children under 13 without
            parental consent.
          </p>
          <h2>CHANGES TO PRIVACY POLICY</h2>
          <p>
            We may update this policy. Continued use of the service implies
            acceptance of updates.
          </p>
          <h2>THIRD-PARTY SERVICES</h2>
          <p>
            Use of third-party services is at your own risk and subject to their
            terms.
          </p>
          <h2>TRACKING TECHNOLOGIES</h2>
          <p>
            Google Maps API may collect device and location data.
            <br />
            Local Storage is used to store client-side data.
          </p>
          <h2>GDPR INFORMATION</h2>
          <p>
            We comply with GDPR standards globally. EU users have rights to
            access, update, delete, or transfer their data.
          </p>
          <h2>CALIFORNIA PRIVACY RIGHTS</h2>
          <p>
            California residents have rights under CCPA and CalOPPA including
            access, deletion, and non-discrimination.
          </p>
          <p>We do not sell personal information.</p>
        </div>
      </main>
      <Footer />
    </>
  );
}
